version: '3'
services:
  mattermost:
    image: mattermost/mattermost-preview
    container_name: mattermost
    networks:
      chatops.net:
        ipv4_address: 172.19.0.2
    ports:
      - 8060:8065
    environment:
      -  MM_SERVICESETTINGS_ALLOWEDUNTRUSTEDINTERNALCONNECTIONS='localhost 0.0.0.0/0 172.19.0.0/16'
  netdata:
      build: ./netdata-master
      container_name: netdata-master
      ports:
        - 19999:19999
      networks:
        chatops.net:
          ipv4_address: 172.19.0.4
  bender:
    image: juniorsntsid/bender
    container_name: bender
    environment:
      - EXPRESS_PORT=8086
      - MATTERMOST_ENDPOINT=/bender/incoming
      - MATTERMOST_TOKEN=hga8h167pff5znokcopi8bd5ge
      - MATTERMOST_INCOME_URL=http://172.19.0.2:8065/hooks/t78pqjm1ujgezea1zkhn7ok9pc
      - HUBOT_LOG_LEVEL=debug
      - HUBOT_GITLAB_URL=https://gitlab.com
      - HUBOT_GITLAB_TOKEN=wBj8cVykYY6qZsz8cbtD
    networks:
      chatops.net:
        ipv4_address: 172.19.0.3
    ports:
      - 8086:8086
networks:
  chatops.net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
